/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CommonService_H
#define CommonService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "common_types.h"

namespace common {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class CommonServiceIf {
 public:
  virtual ~CommonServiceIf() {}
  virtual void ping() = 0;
};

class CommonServiceIfFactory {
 public:
  typedef CommonServiceIf Handler;

  virtual ~CommonServiceIfFactory() {}

  virtual CommonServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(CommonServiceIf* /* handler */) = 0;
  };

class CommonServiceIfSingletonFactory : virtual public CommonServiceIfFactory {
 public:
  CommonServiceIfSingletonFactory(const ::std::shared_ptr<CommonServiceIf>& iface) : iface_(iface) {}
  virtual ~CommonServiceIfSingletonFactory() {}

  virtual CommonServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(CommonServiceIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<CommonServiceIf> iface_;
};

class CommonServiceNull : virtual public CommonServiceIf {
 public:
  virtual ~CommonServiceNull() {}
  void ping() override {
    return;
  }
};


class CommonService_ping_args {
 public:

  CommonService_ping_args(const CommonService_ping_args&) noexcept;
  CommonService_ping_args& operator=(const CommonService_ping_args&) noexcept;
  CommonService_ping_args() noexcept;

  virtual ~CommonService_ping_args() noexcept;

  bool operator == (const CommonService_ping_args & /* rhs */) const;
  bool operator != (const CommonService_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CommonService_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CommonService_ping_pargs {
 public:


  virtual ~CommonService_ping_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CommonService_ping_result {
 public:

  CommonService_ping_result(const CommonService_ping_result&) noexcept;
  CommonService_ping_result& operator=(const CommonService_ping_result&) noexcept;
  CommonService_ping_result() noexcept;

  virtual ~CommonService_ping_result() noexcept;

  bool operator == (const CommonService_ping_result & /* rhs */) const;
  bool operator != (const CommonService_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CommonService_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CommonService_ping_presult {
 public:


  virtual ~CommonService_ping_presult() noexcept;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class CommonServiceClient : virtual public CommonServiceIf {
 public:
  CommonServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  CommonServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping() override;
  void send_ping();
  void recv_ping();
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class CommonServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<CommonServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (CommonServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  CommonServiceProcessor(::std::shared_ptr<CommonServiceIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &CommonServiceProcessor::process_ping;
  }

  virtual ~CommonServiceProcessor() {}
};

class CommonServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  CommonServiceProcessorFactory(const ::std::shared_ptr< CommonServiceIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< CommonServiceIfFactory > handlerFactory_;
};

class CommonServiceMultiface : virtual public CommonServiceIf {
 public:
  CommonServiceMultiface(std::vector<std::shared_ptr<CommonServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~CommonServiceMultiface() {}
 protected:
  std::vector<std::shared_ptr<CommonServiceIf> > ifaces_;
  CommonServiceMultiface() {}
  void add(::std::shared_ptr<CommonServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class CommonServiceConcurrentClient : virtual public CommonServiceIf {
 public:
  CommonServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  CommonServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping() override;
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
